// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
//       <body>{children}</body>
//     </html>
//   );
// }

// app/layout.js
import './globals.css'; // Mantiene los estilos generales del proyecto
import Link from 'next/link';
import styles from './layout.module.css';

export const metadata = {
  title: 'Sistema de Gestión de Beneficiarios',
  description: 'Proyecto escolar de gestión de datos utilizando Next.js y MySQL',
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        {/* Navbar global */}
        <nav className={styles.navbar}>
          <div className={styles.navContainer}>
            <Link href="/" className={styles.logo}>
              BeneficiariosApp
            </Link>
            <ul className={styles.navLinks}>
              <li><Link href="/">Inicio</Link></li>
              <li><Link href="/beneficiarios">Beneficiarios</Link></li>
              <li><Link href="/convocatorias">Convocatorias</Link></li>
              <li><Link href="/sisben">SISBEN</Link></li>
              <li><Link href="/grupos-etnicos">G. Étnicos</Link></li>
              <li><Link href="/modalidades">Modalidades</Link></li>
              <li><Link href="/sectores">Sectores</Link></li>
              <li><Link href="/zonas">Zonas</Link></li>
            </ul>
          </div>
        </nav>
        
        {/* Contenido dinámico de cada página */}
        <main className={styles.mainContent}>
          {children}
        </main>
      </body>
    </html>
  );
}